url: http://integration-engines.com/schoolsopen
baseurl: http://integration-engines.com/schoolsopen

# Site settings
title: SchoolsOPEN
email: info@schools-open.com
description: "SchoolsOPEN is Michigan's premier provider of Fincial and Payroll solutions for Michigan public schools and academies, private schools, and community colleges."

#collections:
#  supplies:
#    output: true
#    permalink: /supplies/:path/

# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 4119 Jackson Rd
  - line: Ann Arbor, MI 48103

# Build settings
markdown: kramdown
permalink: pretty
#theme: agency-jekyll-theme
